### ISSUE TITLE
S24 Ultra if mqtt set it crashes on oneplus 7t pro it still works

### ISSUE THREAD

**Issue by Pjedr** [oliexdev/openScale#1024]
**Describe the bug**
A clear and concise description of what the bug is.Build version: 0.3.5 
Build date: 1981-01-01 01:01:02 
Current date: 2024-03-01 22:38:34 
Device: Samsung SM-S928B 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.SecurityException: com.health.openscale.sync: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6143)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
	at i4.a.start(:2)
	at t5.b.q(:9)
	at t5.d.run(Unknown Source:91)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16597)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11555)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2936)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3198)
	at android.os.Binder.execTransactInternal(Binder.java:1375)

**To Reproduce**

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/dev-build): ???

**Expected behavior**

**Additional context**

**Debug log**
Attach a debug log (see Settings -> About -> Save debug log to file) that is captured while reproducing the issue.

**Comment by Jackahack** [comment]
this is an android api thing.  which the devs need to fix. i made an feature request for this with a link which explains it.  
if your s24 runs android 14 and your oneplus runs android 13 that would explain the why the one works and why the other does not.  mqtt recievers to specify a certain flag when targeting a android api level 34 or higher (android 14 and up). in android 13 this was not needed.

**Comment by oliexdev** [comment]
should be fixed.
