### ISSUE TITLE
Crash on Google Fit Sync

### ISSUE THREAD

**Issue by carlesm** [oliexdev/openScale#1032]
**Describe the bug**

**To Reproduce**
1. Go to Google Fit
2. Click on Manual Sync
3. See error

**Expected behavior**
Manual sync with google fit.

**Additional context**
Build version: 0.3.5 
Build date: 1981-01-01 01:01:02 
Current date: 2024-04-15 08:16:05 
Device: Xiaomi 2201117PG 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.IllegalArgumentException: Data point does not have the timestamp set: DataPoint{[86.5]@[0, 0,raw=0](r:weight:com.health.openscale.sync: N/A)}
	at t1.o.c(Unknown Source:9)
	at com.google.android.gms.fitness.data.DataSet$a.a(:12)
	at com.health.openscale.sync.core.sync.a.d(:11)
	at e4.a$c.onClick(:12)
	at android.view.View.performClick(View.java:7575)
	at android.view.View.performClickInternal(View.java:7548)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29848)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by oliexdev** [comment]
Regarding synchronization with health services, please note that **Google Fit is no longer being actively supported by Google**, and the Google Fit API has been deprecated.

As a result, I have transitioned the synchronization functionality in openScale sync to use **Health Connect** instead. Health Connect is the new standard for managing health and fitness data on Android.

The upcoming beta version (0.4) of openScale sync includes this transition to Health Connect and features a complete rewrite of the application. If you'd like to help test the new Health Connect integration and see if this issue is resolved in the updated version, please consider joining the beta program. You can find more details and instructions on how to join in our pinned beta testing invitation issue here: https://github.com/oliexdev/openScale/issues/1124
