### ISSUE TITLE
[Bug] ActivityNotFoundException in Reminders settings

### ISSUE THREAD

**Issue by LoHub** [oliexdev/openScale#1076]
**Describe the bug**

App show the message *An unexpected error occurred* in *Reminders* settings.

**To Reproduce**

1. Disable *Notification* permission
1. Go in menu bruger
2. Click on *Settings*
3. Go to *Reminders*
4. Click on *OK* to *Notification permission is required, to shox notification*

Reproduced with 2.5.2

**Expected behavior**

No crash and settings panel is displayed normally.

**Debug log**

```
Build version: 2.5.2 
Build date: 1981-01-01 01:01:02 
Current date: 2024-09-29 20:41:00 
Device: Google Pixel 8 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2441)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2011)
	at android.app.Activity.startActivityForResult(Activity.java:5886)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:763)
	at android.app.Activity.startActivityForResult(Activity.java:5806)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:744)
	at android.app.Activity.startActivity(Activity.java:6348)
	at android.app.Activity.startActivity(Activity.java:6315)
	at com.health.openscale.gui.preferences.ReminderPreferences$3.onClick(ReminderPreferences.java:189)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:175)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by oliexdev** [comment]
Thanks for the hint should be fixed now.
