### ISSUE TITLE
App crash while granting Bluetooth permission

### ISSUE THREAD

**Issue by oliexdev** [oliexdev/openScale#244]
@erijo in the current dev version the app crash while granting the location permission in the Bluetooth preference view.

```
04-15 11:19:13.790 23885-23885/com.health.openscale E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }} to activity {com.health.openscale/com.health.openscale.gui.activities.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOnDismissListener(android.content.DialogInterface$OnDismissListener)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOnDismissListener(android.content.DialogInterface$OnDismissListener)' on a null object reference
        at com.health.openscale.gui.preferences.BluetoothPreferences.startBluetoothDiscovery(BluetoothPreferences.java:92)
        at com.health.openscale.gui.preferences.BluetoothPreferences.onMyOwnRequestPermissionsResult(BluetoothPreferences.java:303)
        at com.health.openscale.gui.activities.SettingsActivity.onRequestPermissionsResult(SettingsActivity.java:110)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7434)
        at android.app.Activity.dispatchActivityResult(Activity.java:7260)
```

Would be great if you can look into it.

**Comment by erijo** [comment]
Thought I tested all that, but apparently not. I'll look into it.

What Android version?

**Comment by oliexdev** [comment]
Android 7.0
Can you reproduce this crash?

**Comment by erijo** [comment]
Yes.
