### ISSUE TITLE
app crash while open widget without saving User information 

### ISSUE THREAD

**Issue by kr-nahid** [oliexdev/openScale#276]
#### Expected behavior
it shouldn't be crash when try to open app widget without saving User information .

#### Actual behavior
when i try to open widget without saving User information it crash and shows me that **An unexpected error occurred** .

#### How to reproduce
* download the app and run it then set up with user information
* then go to settings and click on users
* now open user  and click on delete icon for remove user
* now go to widgets and find  open Scale widget
* then put it on home screen and it wants to configure widget
* now click on save and note the bug

> Browser/App version: openScale v1.8.1
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=zf4CTh7eX6I

```
Build version: 1.8.1 
Current date: 2018-05-28 16:43:52 
Device: Symphony V75 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.get(ArrayList.java:310)
	at com.health.openscale.gui.widget.WidgetConfigure$1.onClick(WidgetConfigure.java:100)
	at android.view.View.performClick(View.java:5265)
	at android.view.View$PerformClick.run(View.java:21534)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

User actions: 
2018-05-28 16:28:23: MainActivity resumed
2018-05-28 16:28:23: MainActivity paused
2018-05-28 16:28:23: UserSettingsActivity created
2018-05-28 16:28:23: UserSettingsActivity resumed
2018-05-28 16:29:15: UserSettingsActivity paused
2018-05-28 16:29:15: MainActivity resumed
2018-05-28 16:29:15: UserSettingsActivity destroyed
2018-05-28 16:29:45: MainActivity paused
2018-05-28 16:31:43: MainActivity resumed
2018-05-28 16:31:45: MainActivity paused
2018-05-28 16:31:45: SettingsActivity created
2018-05-28 16:31:45: SettingsActivity resumed
2018-05-28 16:31:46: SettingsActivity paused
2018-05-28 16:31:46: SettingsActivity created
2018-05-28 16:31:46: SettingsActivity resumed
2018-05-28 16:31:48: SettingsActivity paused
2018-05-28 16:31:48: UserSettingsActivity created
2018-05-28 16:31:48: UserSettingsActivity resumed
2018-05-28 16:31:59: MainActivity destroyed
2018-05-28 16:31:59: MainActivity created
2018-05-28 16:31:59: MainActivity resumed
2018-05-28 16:31:59: MainActivity paused
2018-05-28 16:31:59: UserSettingsActivity paused
2018-05-28 16:32:00: SettingsActivity resumed
2018-05-28 16:32:00: UserSettingsActivity destroyed
2018-05-28 16:32:28: SettingsActivity paused
2018-05-28 16:32:28: SettingsActivity resumed
2018-05-28 16:32:28: SettingsActivity destroyed
2018-05-28 16:32:30: SettingsActivity paused
2018-05-28 16:32:30: SettingsActivity created
2018-05-28 16:32:30: SettingsActivity resumed
2018-05-28 16:32:53: SettingsActivity paused
2018-05-28 16:32:53: UserSettingsActivity created
2018-05-28 16:32:53: UserSettingsActivity resumed
2018-05-28 16:33:29: UserSettingsActivity paused
2018-05-28 16:35:59: UserSettingsActivity resumed
2018-05-28 16:36:05: UserSettingsActivity paused
2018-05-28 16:36:05: SettingsActivity resumed
2018-05-28 16:36:05: UserSettingsActivity destroyed
2018-05-28 16:36:06: SettingsActivity paused
2018-05-28 16:36:12: WidgetConfigure created
2018-05-28 16:36:12: WidgetConfigure resumed
```

**Comment by erijo** [comment]
Thank you for your report. Should be fixed now.
