### ISSUE TITLE
Scale support for QN-Scale

### ISSUE THREAD

**Issue by vanadario** [oliexdev/openScale#373]
Hi,

I was happy to see that I can connect my QN-Scale from [Yolanda](http://www.yolanda.hk/#) to openScale since version 1.8.4:
![openscale_bluetooth_menu_screenshot](https://user-images.githubusercontent.com/46424989/50740258-29a2cd00-11ec-11e9-8f23-1aee17f3016d.png)

Unfortunately only the weight is shown.
Additionally the weight seems to be read several times while the measuring is still running and that results in several entries for one measurement procedure in the table in openScale.

I would like to mention at the beginning that the vendor offers to open the API:
[http://www.yolanda.hk/en/customization.html](http://www.yolanda.hk/en/customization.html)
Perhaps it is the easiest way to ask for help there?

I followed step 1 and 2 [here](https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale) anyway but wasn't very successful with step 3.
I was able to identify the weight in all logs, I will mention the package no. with every measurement. The weight is in byte 15 and 16, multiplied with 100 in big endian.
But the weight seems to be transferred repeatedly in almost identical packages during the measurement, probably explaining that there are several entries in the table of openScale.
But I was not able to identify data like height or sex in the packages transferred to the scale, so the BMI and fat seems to be calculated in the vendor's app. But I was also not able to identify something looking like the impedance in the packages transferred from the scale. But it must be sent after these several identcal packages with the weight, because openScale already shows these entries and only after this the scale seems to measure the impedance.

Data from step 1:
1. measurement:
[btsnoop_hci_1.log](https://github.com/oliexdev/openScale/files/2730755/btsnoop_hci_1.log)
![btsnoop_hci_1_screenshot](https://user-images.githubusercontent.com/46424989/50740297-cbc2b500-11ec-11e9-9420-ed2ec9378ec8.png)
Package No. 49

2. measurement:
[btsnoop_hci_2.log](https://github.com/oliexdev/openScale/files/2730756/btsnoop_hci_2.log)
![btsnoop_hci_2_screenshot](https://user-images.githubusercontent.com/46424989/50740303-e006b200-11ec-11e9-8ad3-14a3815b791e.png)
Package No. 49

3. measurement:
[btsnoop_hci_3.log](https://github.com/oliexdev/openScale/files/2730757/btsnoop_hci_3.log)
![btsnoop_hci_3_screenshot](https://user-images.githubusercontent.com/46424989/50740309-e9901a00-11ec-11e9-80c3-68bcae72d0d9.png)
Package No. 43

4. measurement (different person):
[btsnoop_hci_4.log](https://github.com/oliexdev/openScale/files/2730758/btsnoop_hci_4.log)
![btsnoop_hci_4_screenshot](https://user-images.githubusercontent.com/46424989/50740312-f90f6300-11ec-11e9-84d5-aa8062e4e65a.png)
Package No. 39

Data from step 2:
1. measurement:
[openScale_2018-12-22_22-24.txt](https://github.com/oliexdev/openScale/files/2730762/openScale_2018-12-22_22-24.txt)

2. measurement:
[openScale_2018-12-22_22-58.txt](https://github.com/oliexdev/openScale/files/2730763/openScale_2018-12-22_22-58.txt)

Here are pictures of the scale, eventually for completing your wiki when it should have been possible to implement the scale:
front:
![20181222_235326](https://user-images.githubusercontent.com/46424989/50740325-3116a600-11ed-11e9-8a39-d86021ed6782.jpg)
back:
![20181222_234255](https://user-images.githubusercontent.com/46424989/50740329-3a077780-11ed-11e9-81af-4a138c451d1b.jpg)

Thank you in advance for trying to support this scale!

**Comment by oliexdev** [comment]
thanks for your log files, if we have more we can test better. Unfortunately, we have to reverse engineer the `libyolanda_calc.so` library. Please read issue #291 for further information.

**Comment by dockerss** [comment]
See - https://github.com/oliexdev/openScale/issues/291#issuecomment-452367604

**Comment by vanadario** [comment]
Thanks for your replies.
I will test the QNScaleDemo-1.0.apk in the next days.

**Comment by oliexdev** [comment]
@vanadario could you provide for measurement 1 and 2 which user you had entered? (sex (male or female), age and body height in cm)

**Comment by vanadario** [comment]
@oliexdev I entered a testuser named "Horst", male, day of birth 02.05.1981 (tt.mm.yyyy, so currently 37 years old), height 178 cm.

I just also tried to install the QNScaleDemo-1.0.apk but it could not be installed without a clear error message. I'm afraid the phone I#m using for these tests is no longer supported, (HTC One mini2 with Android 4.4.2).
My current phone is owned by my company. When I activate sideloading of apps there the KNOX-workspace would be deleted imediately, so I can't try it with this one...

**Comment by oliexdev** [comment]
@vanadario did you use the same user information for both measurements?

**Comment by vanadario** [comment]
@oliexdev Yes, for measurements 1, 2, 3 I used the same.
For measurement 4 I used another one, female, 176 cm, 33 years old.

**Comment by vanadario** [comment]
@oliexdev Since the update to version 1.9 (37) it works with my QN-Scale, values are no longer transferred repeatedly and also body fat etc. are displayed.
Thank you very much!
The values for body fat etc. differ from the values in the vendor's app, but I assume that's just due to the estimation formula the app uses? For me the value itself is not the relevant but the trend.

![screenshot_20190124-060832_openscale](https://user-images.githubusercontent.com/46424989/51656679-599af000-1fa2-11e9-8ec6-c3f844d5f77d.jpg)
![screenshot_20190124-060056_yolanda](https://user-images.githubusercontent.com/46424989/51656690-661f4880-1fa2-11e9-894e-570de2ce6dee.jpg)

**Comment by dockerss** [comment]
@vanadario what is the vendor app? Can you share a link?
I was getting a body fat reading of +-2% when compared with fitindex app.
You can look at the logs for
 resistance1: 
 resistance2: 
and share the values

**Comment by vanadario** [comment]
> 
> 
> @vanadario what is the vendor app? Can you share a link? Is it this one http://www.yolanda.hk/mobile/apps/oversea_app_down

Your link doesn't work now. I use this one:
https://play.google.com/store/apps/details?id=com.yolanda.foreign&hl=en_US

> I was getting a body fat reading of +-2% when compared with fitindex app. https://play.google.com/store/apps/details?id=com.qingniu.fitindex
> You can look at the logs for
> resistance1:
> resistance2:
> and share the values

I compared Fitindex, Yolanda and openScale. Values in Fitindex and Yolanda are almost the same, it even seems to be the same app with a different theme. Screenshots below.

Can you give me a hint where I can find the logs? I even can't find a data folder for Yolanda or Fitindex in Android/data.

Fitindex:
![screenshot_20190201-082845_fitindex](https://user-images.githubusercontent.com/46424989/52109512-11ad4600-25fe-11e9-8105-35ba6e874b6d.jpg)

Yolanda:
![screenshot_20190201-082903_yolanda](https://user-images.githubusercontent.com/46424989/52109519-196cea80-25fe-11e9-92e0-9081f47f876b.jpg)

openScale:
![screenshot_20190201-082830_openscale](https://user-images.githubusercontent.com/46424989/52109527-1f62cb80-25fe-11e9-8cd6-f6ee09936a80.jpg)

**Comment by srwareham** [comment]
Can this issue be closed? 

If so, I believe the wiki can be updated with a new scale "QN-Scale" with the image above and details identical to the FITINDEX ES-26M one in #434

**Comment by oliexdev** [comment]
@srwareham well I don't think so. Currently, the QN-Scale uses the Trisa Body Analyse library but somebody has to be reverse engineered the original `libyolanda_calc.so` library to get the correct values of the body measurements.

**Comment by Aypac** [comment]
It appears to me like this exact scale is sold under many vendor names. I have a version from "RENPHO" (same model number though).
 <details>
  <summary>Show/Hide pictures</summary>
  <img src="https://user-images.githubusercontent.com/10585956/74591144-c487f080-5015-11ea-85e2-f2c7c2954894.jpg" />
<img src="https://user-images.githubusercontent.com/10585956/74591146-c5208700-5015-11ea-9fed-6871579e9cb1.jpg" />
<img src="https://user-images.githubusercontent.com/10585956/74591145-c5208700-5015-11ea-80e4-742d7fcefdad.jpg" />
</details> 

As a result in the [propriety app](https://play.google.com/store/apps/details?id=com.qingniu.renpho&hl=en) I get

<img src="https://user-images.githubusercontent.com/10585956/74591253-a373cf80-5016-11ea-964a-6865d3603f8e.png" width="400px" />
while I get
<img src="https://user-images.githubusercontent.com/10585956/74591323-53493d00-5017-11ea-9bd9-6b4245240485.png" width="400px" />
from this app.

 <details>
  <summary>Show/Hide raw data</summary>
"biceps","bone","caliper1","caliper2","caliper3","calories","chest","comment","dateTime","fat","hip","lbm","muscle","neck","thigh","visceralFat","waist","water","weight"
0.0,4.786194,0.0,0.0,0.0,0.0,0.0,"","2020-02-15 17:06",15.9795,0.0,0.0,45.815155,0.0,0.0,0.0,0.0,61.873444,70.4
</details>

I'll try and post some btsnoop data later, if that would help.

**Comment by mzzntn** [comment]
I also have a scale that appears on Bluetooth devices as QN-S500. The scale is sold by Kamtron, in my particular case.

If you need any data or information to be able to support it, I'm here to help :)

**Comment by fooxax** [comment]
Hey all, 
Just to add another scale sold as "Hutbit" and identified as QN-Scale. The official app is called feelfit but as mentioned earlier seems to be similar to other apps which are linked to QN-Scales.

![Screenshot_20210207-111507_Feelfit_1](https://user-images.githubusercontent.com/61119555/107143582-208a0a00-6936-11eb-9e9f-459d5935034a.png)
![Screenshot_20210207-111557_openScale](https://user-images.githubusercontent.com/61119555/107143590-2a137200-6936-11eb-971b-d4ce315dbc72.png)

The most interesting things to know,  besides of what already works,  are body fat and muscle mass.  Will see if I can find a matching formula.

**Comment by gammerboy** [comment]
It seems the same scale is sold as Actofit smartscale lite in India. Which showed up as QN-scale under bluetooth but didn't connect in their own app. Not sure if they are using a different firmware in their device and I got one which did not got pushed out with the manufacturer firmware.

**Comment by gammerboy** [comment]
It looks exactly the as the photo posted by the op. Openscale crashes when trying to connect to it. I'm not sure if it has some other firmware running on it tho. 

`Build version: 2.3.2-dev_5d697fe9_2020-11-05 
Build date: 1981-01-01 01:01:02 
Current date: 2021-09-28 19:00:38 
Device: OnePlus ONEPLUS A3003 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.NullPointerException: no valid characteristic provided
	at java.util.Objects.requireNonNull(Objects.java:245)
	at com.welie.blessed.BluetoothPeripheral.writeCharacteristic(BluetoothPeripheral.java:1192)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.writeBytes(BluetoothCommunication.java:200)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.writeBytes(BluetoothCommunication.java:188)
	at com.health.openscale.core.bluetooth.BluetoothQNScale.onNextStep(BluetoothQNScale.java:111)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:460)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:462)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:462)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.resumeMachineState(BluetoothCommunication.java:173)
	at com.health.openscale.core.bluetooth.BluetoothCommunication$1.onServicesDiscovered(BluetoothCommunication.java:329)
	at com.welie.blessed.BluetoothPeripheral$1$1.run(BluetoothPeripheral.java:381)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

**Comment by oliexdev** [comment]
Since there has been no progress on this issue for a long time, I am closing it for now.  

Please note that implementation of new scale support requires access to the **actual scale**.

If someone wants to continue working on this, feel free to **reopen this issue** or submit a working implementation via a **pull request**.

For guidance on how to add a new scale handler into openScale, see the updated wiki page:  **[How to support a new scale](https://github.com/oliexdev/openScale/wiki/How-to-support-a-new-scale)**
