### ISSUE TITLE
 Binary XML file error

### ISSUE THREAD

**Issue by leonardoafonso90** [oliexdev/openScale#406]
Build version: 2.0 
Build date: 1979-11-30 00:00:00 
Current date: 2019-02-23 17:23:14 
Device: LGE LG-D855 

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.health.openscale/com.health.openscale.gui.MainActivity}: android.view.InflateException: Binary XML file line #126: Binary XML file line #126: Error inflating class <unknown>
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
at android.app.ActivityThread.access$900(ActivityThread.java:157)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5551)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: android.view.InflateException: Binary XML file line #126: Binary XML file line #126: Error inflating class <unknown>
at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
at com.health.openscale.gui.fragments.GraphFragment.onCreateView(GraphFragment.java:111)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2440)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:885)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2605)
at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2565)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:245)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:525)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:179)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
at android.app.Activity.performStart(Activity.java:6288)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
... 9 more
Caused by: android.view.InflateException: Binary XML file line #126: Error inflating class <unknown>
at android.view.LayoutInflater.createView(LayoutInflater.java:645)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
... 23 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at android.view.LayoutInflater.createView(LayoutInflater.java:619)
... 28 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1723)
at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1792)
at android.graphics.drawable.RippleDrawable$RippleState.<init>(RippleDrawable.java:982)
at android.graphics.drawable.RippleDrawable.createConstantState(RippleDrawable.java:973)
at android.graphics.drawable.RippleDrawable.createConstantState(RippleDrawable.java:96)
at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1652)
at android.graphics.drawable.RippleDrawable.mutate(RippleDrawable.java:959)
at android.view.View.applyBackgroundTint(View.java:17485)
at android.view.View.setBackgroundDrawable(View.java:17361)
at com.google.android.material.floatingactionbutton.FloatingActionButton.access$101(FloatingActionButton.java:97)
at com.google.android.material.floatingactionbutton.FloatingActionButton$ShadowDelegateImpl.setBackgroundDrawable(FloatingActionButton.java:1384)
at com.google.android.material.floatingactionbutton.FloatingActionButtonImplLollipop.setBackgroundDrawable(FloatingActionButtonImplLollipop.java:80)
at com.google.android.material.floatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:244)
at com.google.android.material.floatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:193)

**Comment by oliexdev** [comment]
see #405
