### ISSUE TITLE
Crash trying to open general settings

### ISSUE THREAD

**Issue by jamessan** [oliexdev/openScale#409]
**Describe the bug**
After upgrading to 2.0, the first launch immediately crashed with the below stack. I'm also able to reproduce the stack by trying to open the general settings menu.

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): Not tried

**Debug log**
[openScale_2019-02-24_07-18.txt](https://github.com/oliexdev/openScale/files/2897872/openScale_2019-02-24_07-18.txt)

Build version: 2.0 
Build date: 1979-11-29 19:00:00 
Current date: 2019-02-24 07:01:06 
Device: Huawei Nexus 6P 
 
Stack trace:  
java.lang.RuntimeException: Unable to start receiver com.health.openscale.gui.widget.WidgetProvider: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
	at android.app.ActivityThread.-wrap17(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:240)
	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:211)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:146)
	at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:78)
	at com.google.android.material.floatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:202)
	at com.google.android.material.floatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:193)
	at com.google.android.material.floatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:189)
	at com.health.openscale.gui.views.MeasurementView.initView(MeasurementView.java:182)
	at com.health.openscale.gui.views.MeasurementView.<init>(MeasurementView.java:88)
	at com.health.openscale.gui.views.FloatMeasurementView.<init>(FloatMeasurementView.java:78)
	at com.health.openscale.gui.views.WeightMeasurementView.<init>(WeightMeasurementView.java:32)
	at com.health.openscale.gui.views.MeasurementView.getMeasurementList(MeasurementView.java:113)
	at com.health.openscale.gui.widget.WidgetProvider.updateWidget(WidgetProvider.java:70)
	at com.health.openscale.gui.widget.WidgetProvider.onUpdate(WidgetProvider.java:158)
	at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
	... 8 more

**Comment by oliexdev** [comment]
thanks should be fixed with commit https://github.com/oliexdev/openScale/commit/e7e8dff7e301d36708fb4594992f62d244aca770
