### ISSUE TITLE
Sanitas SBF 70 - an unexp. err occurred

### ISSUE THREAD

**Issue by rptnscz** [oliexdev/openScale#475]
**Describe the bug**
Build version: 2.1.0-pro 
Current date: 2019-06-23 06:51:57 
Device: Sony H4213 
 
Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'boolean com.health.openscale.core.bluetooth.BluetoothBeurerSanitas$RemoteUser.isNew' on a null object reference
	at com.health.openscale.core.bluetooth.BluetoothBeurerSanitas.onNextStep(BluetoothBeurerSanitas.java:237)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:434)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.access$000(BluetoothCommunication.java:44)
	at com.health.openscale.core.bluetooth.BluetoothCommunication$1.onCharacteristicWrite(BluetoothCommunication.java:327)
	at com.welie.blessed.BluetoothPeripheral$1$9.run(BluetoothPeripheral.java:563)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by oliexdev** [comment]
see #470
