### ISSUE TITLE
Fehler bei Sanitas Waage

### ISSUE THREAD

**Issue by WolframSchmidtRS** [oliexdev/openScale#545]
**Describe the bug**

**To Reproduce**

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???

**Expected behavior**

**Additional context**

**Debug log**
Attach a debug log (see Settings -> About -> Save debug log to file) that is captured while reproducing the issue.

**Comment by WolframSchmidtRS** [comment]
Nach der Verbindungsaufnahme kommt folgende Fehlermeldung:

Build version: 2.2.0-pro 
Current date: 2020-01-25 13:11:32 
Device: HUAWEI VOG-L29 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = ')'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2781)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2811)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2842)
	at com.health.openscale.gui.MainActivity$10.handleMessage(MainActivity.java:568)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by WolframSchmidtRS** [comment]
Es handel sich um die Sanitas Waage

**Comment by oliexdev** [comment]
Could you attach the openScale log file? Check the FAQ to see how it works. Please also indicate which language your application has used.
