### ISSUE TITLE
App crashes after successfully connecting to scale

### ISSUE THREAD

**Issue by mckym** [oliexdev/openScale#583]
**Describe the bug**
Since 1 week the app started crashing once the bt connection has been established. Scales used: SBF 70

**To Reproduce**
1. Start App
2. Wait for app to display: connection established
3. App crashes

Reproduced with latest version from play store.

**Expected behavior**
No crash

**Debug log**
Build version: 2.2.0-pro 
Current date: 2020-06-07 11:29:24 
Device: Xiaomi Mi A2 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = ')'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2782)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2812)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2625)
	at java.util.Formatter.parse(Formatter.java:2558)
	at java.util.Formatter.format(Formatter.java:2505)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2870)
	at com.health.openscale.gui.MainActivity$10.handleMessage(MainActivity.java:568)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by oliexdev** [comment]
see #577
