### ISSUE TITLE
Bug on initial user creation

### ISSUE THREAD

**Issue by Phenitei** [oliexdev/openScale#595]
Hi,

When installing from F-Droid, clicking the "add user" in the intro panels consistently makes the app crash.

```
Build version: 2.3.0 
Build date: 1980-01-01 00:00:00 
Current date: 2020-07-08 00:26:18 
Device: LGE Nexus 5X 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.health.openscale/com.health.openscale.gui.slides.SlideToNavigationAdapter}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2742)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6171)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
	at androidx.appcompat.app.AppCompatDelegateImpl.setSupportActionBar(AppCompatDelegateImpl.java:421)
	at androidx.appcompat.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:150)
	at com.health.openscale.gui.slides.SlideToNavigationAdapter.onCreate(SlideToNavigationAdapter.java:43)
	at android.app.Activity.performCreate(Activity.java:6682)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2634)
	... 9 more
```

Please ask for any other information you might need, and thank you for your awesome work!

**Comment by oliexdev** [comment]
thanks for reporting, should be fixed now.
