### ISSUE TITLE
App crash when trying to get data from scale SBF75

### ISSUE THREAD

**Issue by talexop** [oliexdev/openScale#596]
**Describe the bug**
App crashes when tries to retrieve data from SBF75 scale

**To Reproduce**
1. Just start the app and wait to connect with scale

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): 2.2.0

**Expected behavior**
Used to worked fine . Don't know what changed!

**Additional context**

**Debug log**
Build version: 2.2.0 
Current date: 2020-07-08 21:58:16 
Device: Samsung SM-N975F 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = ')'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2782)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2812)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2625)
	at java.util.Formatter.parse(Formatter.java:2558)
	at java.util.Formatter.format(Formatter.java:2505)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2870)
	at com.health.openscale.gui.MainActivity$10.handleMessage(MainActivity.java:568)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by oliexdev** [comment]
see #583
