### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Melmot** [oliexdev/openScale#601]
An error occurs within a second of application launch - just enough to catch a glimpse of the interface.

System: Android 7.1.1

Error message:

Build version: 2.2.0-pro 
Current date: 2020-07-21 17:21:05 
Device: Sony E5823 
 
Stack trace:  
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@dab7e0a is not valid; is your activity running?
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:341)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
 at android.widget.Toast$TN.handleShow(Toast.java:535)
 at android.widget.Toast$TN$3.handleMessage(Toast.java:356)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:241)
 at android.app.ActivityThread.main(ActivityThread.java:6274)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by oliexdev** [comment]
strange could you try to uninstall and install openScale again? Does this error occur again?
