### ISSUE TITLE
error first time making user

### ISSUE THREAD

**Issue by Xylon2** [oliexdev/openScale#602]
**Describe the bug**
stack trace

**To Reproduce**
- on a Fairphone 3
- install openscale from f-droid
- try to make user from startup wizard
- see error

**Debug log**
Build version: 2.3.0 
Build date: 1979-11-30 00:00:00 
Current date: 2020-07-22 12:15:53 
Device: Fairphone FP3 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.health.openscale/com.health.openscale.gui.slides.SlideToNavigationAdapter}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2952)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6746)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
	at androidx.appcompat.app.AppCompatDelegateImpl.setSupportActionBar(AppCompatDelegateImpl.java:421)
	at androidx.appcompat.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:150)
	at com.health.openscale.gui.slides.SlideToNavigationAdapter.onCreate(SlideToNavigationAdapter.java:43)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932)
	... 11 more

**Comment by oliexdev** [comment]
see issue #595
