### ISSUE TITLE
exception on dialog switch

### ISSUE THREAD

**Issue by alexanderadam** [oliexdev/openScale#617]
**Describe the bug**

I just switched to another view and an exception happened. But maybe the cause was something else because there's only Bluetooth stuff in the backtrace.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Home Icon
2. Click on the Icon right beside it
3. See error

Reproduced with [latest F-Droid version](https://f-droid.org/en/packages/com.health.openscale/#2.3.1): `v2.3.1 (50)`

**Expected behavior**
Everything works

**Debug log**

```
Build version: 2.3.1 
Build date: 1979-11-30 01:00:00 
Current date: 2020-08-26 18:34:02 
Device: Samsung SM-G960F 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.view.ViewConfiguration.get(ViewConfiguration.java:491)
	at android.view.View.<init>(View.java:5439)
	at android.view.View.<init>(View.java:5631)
	at android.view.ViewGroup.<init>(ViewGroup.java:687)
	at android.widget.LinearLayout.<init>(LinearLayout.java:254)
	at android.widget.LinearLayout.<init>(LinearLayout.java:250)
	at android.widget.LinearLayout.<init>(LinearLayout.java:246)
	at android.widget.LinearLayout.<init>(LinearLayout.java:242)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$BluetoothDeviceView.<init>(BluetoothSettingsFragment.java:264)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$2.run(BluetoothSettingsFragment.java:155)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8125)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by oliexdev** [comment]
thanks, should be fixed, please try out the latest dev build.
