### ISSUE TITLE
crash during initial setup

### ISSUE THREAD

**Issue by tjeulink** [oliexdev/openScale#619]
Hi there! The app crashed while going through the first time startup menu thingies. It asked me to post the crash log here to help the app so here they are. It didnt list my bluetooth scale so i skipped that step and soon after it crashed.

```
Build version: 2.3.1 
Build date: 1979-11-30 01:00:00 
Current date: 2020-08-30 22:36:40 
Device: Fairphone FP3 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.view.ViewConfiguration.get(ViewConfiguration.java:447)
	at android.view.View.<init>(View.java:4806)
	at android.view.View.<init>(View.java:4948)
	at android.view.ViewGroup.<init>(ViewGroup.java:659)
	at android.widget.LinearLayout.<init>(LinearLayout.java:244)
	at android.widget.LinearLayout.<init>(LinearLayout.java:240)
	at android.widget.LinearLayout.<init>(LinearLayout.java:236)
	at android.widget.LinearLayout.<init>(LinearLayout.java:232)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$BluetoothDeviceView.<init>(BluetoothSettingsFragment.java:264)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.onDeviceFound(BluetoothSettingsFragment.java:191)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.access$000(BluetoothSettingsFragment.java:69)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$1.onDiscoveredPeripheral(BluetoothSettingsFragment.java:129)
	at com.welie.blessed.BluetoothCentral$2$1.run(BluetoothCentral.java:170)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6746)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by oliexdev** [comment]
thanks, should be fixed, please try out the latest dev build.
