### ISSUE TITLE
Crash when adding new point from scale

### ISSUE THREAD

**Issue by jimbolaya** [oliexdev/openScale#654]
**Describe the bug**
After I connect with the scale, and finish weighing myself, the app crashes

**To Reproduce**
1. Upgrade to 2.3.2 from earlier version
2. Click on the Bluetooth icon to start Bluetooth connection
3. Step on scale to get weight, when done, step off
4. App Crashes

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): 2.3.2

**Expected behavior**
I expect the app not to crash

**Additional context**
This is the F-Droid version

**Debug log**
Build version: 2.3.2 
Build date: 1981-01-01 01:01:02 
Current date: 2020-11-22 07:48:15 
Device: Motorola moto x4 
OS version: Android 9 (SDK 28) 
 
Stack trace:  
java.lang.IllegalArgumentException: MONTH
	at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2662)
	at java.util.Calendar.updateTime(Calendar.java:3397)
	at java.util.Calendar.getTimeInMillis(Calendar.java:1761)
	at com.health.openscale.core.bluetooth.BluetoothOneByone.parseBytes(BluetoothOneByone.java:223)
	at com.health.openscale.core.bluetooth.BluetoothOneByone.onBluetoothNotify(BluetoothOneByone.java:125)
	at com.health.openscale.core.bluetooth.BluetoothCommunication$1.onCharacteristicUpdate(BluetoothCommunication.java:358)
	at com.welie.blessed.BluetoothPeripheral$1$5.run(BluetoothPeripheral.java:461)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6912)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by oliexdev** [comment]
see #646
