### ISSUE TITLE
Continue crash during startup

### ISSUE THREAD

**Issue by Bullet111** [oliexdev/openScale#661]
**Describe the bug**
The app crashes continuously during startup

**To Reproduce**
1. Go to the app
2. Click on openScale pro

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): 2.3.3-pro

**Expected behavior**
I Hope that you can fix It, I love this app. Thanks

**Debug log**
Build version: 2.3.3-pro 
Build date: 1981-01-01 01:01:02 
Current date: 2020-12-01 08:07:27 
Device: Xiaomi POCO F2 Pro 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at com.health.openscale.core.utils.PolynomialFitter.gj_swap(PolynomialFitter.java:186)
	at com.health.openscale.core.utils.PolynomialFitter.gj_echelonize(PolynomialFitter.java:156)
	at com.health.openscale.core.utils.PolynomialFitter.getBestFit(PolynomialFitter.java:118)
	at com.health.openscale.gui.measurement.ChartMeasurementView.addPredictionLine(ChartMeasurementView.java:539)
	at com.health.openscale.gui.measurement.ChartMeasurementView.addTrendLine(ChartMeasurementView.java:516)
	at com.health.openscale.gui.measurement.ChartMeasurementView.refreshMeasurementList(ChartMeasurementView.java:392)
	at com.health.openscale.gui.measurement.ChartMeasurementView.updateMeasurementList(ChartMeasurementView.java:347)
	at com.health.openscale.gui.overview.OverviewFragment.updateOnView(OverviewFragment.java:264)
	at com.health.openscale.gui.overview.OverviewFragment$8.onChanged(OverviewFragment.java:239)
	at com.health.openscale.gui.overview.OverviewFragment$8.onChanged(OverviewFragment.java:236)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by oliexdev** [comment]
see #645 and https://github.com/oliexdev/openScale/issues/645#issuecomment-732851143

What kind of data do you have? How many? How does it looks like? I need more info as described in #645
