### ISSUE TITLE
Sudden crash? 

### ISSUE THREAD

**Issue by Tumpen1** [oliexdev/openScale#711]
Hello good people,

Opened and used it as I'm used to in the morning for over a year, after connection between scale and app data loaded fine, but changing from table view to first page overview, all data was "lumped" to the right, I tried changing from day view to week and app crashed with no amount of retries or reboots getting it going again.

**Phone:** 
Oneplus 6T ( A6013_41210121 )
Android 10 ( OxygenOs 10.3.8 )

**Scale:** 
Beurer BF-710 (pink if it matters)

**Copy paste from chrash:**
Build version: 2.1.0-dev_158b0303_2019-06-26 
Current date: 2021-03-07 05:18:52 
Device: OnePlus ONEPLUS A6013 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=1614817; index=1641427
	at com.health.openscale.gui.views.ChartMeasurementView.averageScaleMeasurementList(ChartMeasurementView.java:524)
	at com.health.openscale.gui.views.ChartMeasurementView.refresh(ChartMeasurementView.java:587)
	at com.health.openscale.gui.views.ChartMeasurementView.setViewRange(ChartMeasurementView.java:139)
	at com.health.openscale.gui.fragments.OverviewFragment.updateChartView(OverviewFragment.java:285)
	at com.health.openscale.gui.fragments.OverviewFragment.updateOnView(OverviewFragment.java:278)
	at com.health.openscale.core.OpenScale.registerFragment(OpenScale.java:635)
	at com.health.openscale.gui.fragments.OverviewFragment.onCreateView(OverviewFragment.java:255)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2646)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2600)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1514)
	at android.app.Activity.performStart(Activity.java:7838)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3398)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

I've tried to upload the .DB file from OpenScaleBackUp folder but get "we dont support that file type" and winrar wont zip it, if it is needed i'll need some help, google managed guiding me to open it in DB Browser SQLite where it seems fine?
If its not clear by now I know very little about software and code. :)  (but i do mess around with hardware alot.)

Any help appricieted! Thank you in advanced.

**Comment by Tumpen1** [comment]
After messing about for a while I realised how old my version was sorry about my ignorance! 
I've managed to recreate the backup.DB to my new install and only lost a weeks worth of measurements i did get a crash on the new install but only one otherwise it seems to be fine.
