### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by hackel** [oliexdev/openScale#768]
Today after starting OpenScale from the reminder notification, as I do almost every day, the app crashed after briefly flashing the UI.  After the error I restarted the app and everything worked as expected.

I have not been able to reproduce the issue.  As far as I know nothing has changed on my device.  I've used OpenScale for a long time, including a month on the current OS version, and never had a problem until now.

I hope this stack trace is useful.  I realize that it's not a lot to go on.

Build version: 2.3.5 
Build date: 1981-01-01 01:01:02 
Current date: 2021-08-21 13:07:44 
Device: Google Pixel 4a 
OS version: Android 12 (SDK 31)  (beta 3.1)
 
Stack trace:  
```
java.lang.NullPointerException: no valid characteristic provided
	at java.util.Objects.requireNonNull(Objects.java:245)
	at com.welie.blessed.BluetoothPeripheral.writeCharacteristic(BluetoothPeripheral.java:1182)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.writeBytes(BluetoothCommunication.java:200)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.writeBytes(BluetoothCommunication.java:188)
	at com.health.openscale.core.bluetooth.BluetoothQNScale.onNextStep(BluetoothQNScale.java:111)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:460)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:462)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:462)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.access$000(BluetoothCommunication.java:46)
	at com.health.openscale.core.bluetooth.BluetoothCommunication$2.onConnectedPeripheral(BluetoothCommunication.java:370)
	at com.welie.blessed.BluetoothCentral$4$1.run(BluetoothCentral.java:250)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7829)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
```

**Comment by oliexdev** [comment]
ok thanks for reporting. Since it happens only one time, I will close this issue. If this occurred once again please reopen this issue.
