### ISSUE TITLE
App won't launch in Android 12

### ISSUE THREAD

**Issue by foleymike** [oliexdev/openScale#780]
**Describe the bug**
On launching the app, the screen goes to 'An unexpected error occurred' page and refuses to go any further.

**Debug log**
Build version: 2.4.1-pro 
Build date: 1981-01-01 01:01:02 
Current date: 2021-10-20 12:27:55 
Device: Google Pixel 4a (5G) 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@90ce40c3: GattService registerScanner
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerScanner(IBluetoothGatt.java:1727)
	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:426)
	at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:278)
	at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:154)
	at com.welie.blessed.BluetoothCentralManager.startScan(BluetoothCentralManager.java:413)
	at com.welie.blessed.BluetoothCentralManager.scanForPeripheralsWithAddresses(BluetoothCentralManager.java:486)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.connect(BluetoothCommunication.java:541)
	at com.health.openscale.core.OpenScale.connectToBluetoothDevice(OpenScale.java:627)
	at com.health.openscale.gui.MainActivity.invokeConnectToBluetoothDevice(MainActivity.java:588)
	at com.health.openscale.gui.MainActivity.onCreateOptionsMenu(MainActivity.java:532)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4277)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by oliexdev** [comment]
thanks the Bluetooth permission handling was changed in Android 12, see https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

I have pushed some changed to hopefully solve this problem but unfortunately I don't own an Android 12 smartphone to test these changes.

Could you try out the latest [openScale dev build](https://github.com/oliexdev/openScale/releases/download/travis-dev-build/openScale-dev-build.apk) on Android 12?

Please report back if it works or not. Thanks in advance!

I will close this issue, please use issue #779 .
