### ISSUE TITLE
Exception when clicking Bluetooth icon

### ISSUE THREAD

**Issue by FredrikWendt** [oliexdev/openScale#783]
I upgraded to Android 12 an hour ago, and now I can't connect.

Permissions (in Swedish, sorry)
![Screenshot_20211030-001435](https://user-images.githubusercontent.com/89504/139507121-ab32c73e-3b21-4476-86c9-7df8d48f8054.png)

Build version: 2.4.1-pro 
Build date: 1981-01-01 01:01:02 
Current date: 2021-10-30 00:12:38 
Device: Google Pixel 5 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@f9f495b4: GattService registerScanner
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerScanner(IBluetoothGatt.java:1727)
	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:426)
	at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:278)
	at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:154)
	at com.welie.blessed.BluetoothCentralManager.startScan(BluetoothCentralManager.java:413)
	at com.welie.blessed.BluetoothCentralManager.scanForPeripheralsWithAddresses(BluetoothCentralManager.java:486)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.connect(BluetoothCommunication.java:541)
	at com.health.openscale.core.OpenScale.connectToBluetoothDevice(OpenScale.java:627)
	at com.health.openscale.gui.MainActivity.invokeConnectToBluetoothDevice(MainActivity.java:588)
	at com.health.openscale.gui.MainActivity.onOptionsItemSelected(MainActivity.java:409)
	at android.app.Activity.onMenuItemSelected(Activity.java:4340)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28676)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by oliexdev** [comment]
thanks the Bluetooth permission handling was changed in Android 12, see https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

I have pushed some changed to hopefully solve this problem but unfortunately I don't own an Android 12 smartphone to test these changes.

Could you try out the latest [openScale dev build](https://github.com/oliexdev/openScale/releases/download/travis-dev-build/openScale-dev-build.apk) on Android 12?

Please report back if it works or not. Thanks in advance!

I will close this issue, please use issue #779 .
