### ISSUE TITLE
gh pr checkout 798

### ISSUE THREAD

**Issue by Tobats1992** [oliexdev/openScale#799]
**Describe the bug**

**To Reproduce**

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???

**Expected behavior**

**Additional context**

**Debug log**
Attach a debug log (see Settings -> About -> Save debug log to file) that is captured while reproducing the issue.[Build version: 2.4.5  Build date: 1981-01-01 01:01:02  Current date: 2021-11-27 22:28:10  Device: OPPO CPH2083  OS version: Android 9 (SDK 28)    Stack trace:   java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.ListView.getCheckedItemPosition()' on a null object reference 	at com.health.openscale.gui.MainActivity$10.onClick(MainActivity.java:487) 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:203) 	at android.os.Handler.dispatchMessage(Handler.java:106) 	at android.os.Looper.loop(Looper.java:233) 	at android.app.ActivityThread.main(ActivityThread.java:7225) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)](https://github.com/oliexdev/openScale/issues/@tobats1992git)

**Comment by Tobats1992** [comment]
https://github.com/oliexdev/openScale/issues/799
