### ISSUE TITLE
Random crashes A12

### ISSUE THREAD

**Issue by sacca97** [oliexdev/openScale#803]
**Describe the bug**
The application just crashes randomly when using it. 

**To Reproduce**
Open and use the application.

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): yes

**Expected behavior**
No crashes.

**Additional context**
None

**Debug log**
Build version: 2.4.5-dev_7b1d9266_2021-11-26 
Build date: 1981-01-01 01:01:02 
Current date: 2021-11-29 10:02:12 
Device: Google Pixel 5 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.IllegalStateException: Fragment BluetoothSettingsFragment{2c7004d} (9a0f6895-3ca9-4be4-9a79-75ea466c366f) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.onDeviceFound(BluetoothSettingsFragment.java:204)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.access$000(BluetoothSettingsFragment.java:69)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$1$1.run(BluetoothSettingsFragment.java:131)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7838)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by jensMF** [comment]
I fixed that in #806
