### ISSUE TITLE
Crash to synch google fit

### ISSUE THREAD

**Issue by awirz77** [oliexdev/openScale#828]
**Describe the bug**
Can t sync with Google fit. Last time it sync was 29/Jan/22

**To Reproduce**
1. Go to Google fit
2. Click on manual sync
3. Crash. Follow the info

Build version: 0.3.2 
Build date: 1979-11-30 00:00:00 
Current date: 2022-02-13 13:48:42 
Device: Motorola edge 20 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.IllegalArgumentException: Data point does not have the timestamp set: DataPoint{[92.46]@[0, 0,raw=0](r:weight:com.health.openscale.sync: N/A)}
	at d.b.a.a.c.l.q.a(Unknown Source:9)
	at com.google.android.gms.fitness.data.DataSet$a.a(:12)
	at d.c.a.a.a.b.a.a(:35)
	at d.c.a.a.b.b.a$c.onClick(:12)
	at android.view.View.performClick(View.java:7465)
	at android.view.View.performClickInternal(View.java:7442)
	at android.view.View.access$3600(View.java:813)
	at android.view.View$PerformClick.run(View.java:28394)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7886)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:970)

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???

**Expected behavior**

**Additional context**

**Debug log**
Attach a debug log (see Settings -> About -> Save debug log to file) that is captured while reproducing the issue.

**Comment by oliexdev** [comment]
In your Google Fit or in your openScale data you have some corrupt data point without a valid timestamp (do you have really old datapoints?)
