### ISSUE TITLE
Silvercrest SBF 77 won`t connect via bluetooth

### ISSUE THREAD

**Issue by wh8box** [oliexdev/openScale#833]
**Describe the bug**
No connections via bluetooth to SBF 77 model. Crashed app, then first run.

**To Reproduce**

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???

**Expected behavior**

**Additional context**
Build version: 2.4.5 
Build date: 1981-01-01 01:01:02 
Current date: 2022-02-26 16:39:04 
Device: Xiaomi M2004J19C 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.IllegalStateException: Fragment BluetoothSettingsFragment{430a1c9} (4ee46ce9-2b92-4849-baca-36e6bfbb39b5) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.onDeviceFound(BluetoothSettingsFragment.java:204)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.access$000(BluetoothSettingsFragment.java:69)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$1$1.run(BluetoothSettingsFragment.java:131)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Debug log**
2022-02-26 16:46:07.875 Debug [2] AboutPreferences: Debug log enabled, openScale v2.4.5 (60), SDK 30, Xiaomi M2004J19C
2022-02-26 16:46:07.880 Debug [2] AboutPreferences: Selected user id(1) name(Pipo) birthday(Tue Feb 26 16:37:06 GMT+02:00 2002) age(20) body height(181.00) scale unit(kg) gender(male) initial weight(72.00) goal weight(65.00) goal date(Fri Aug 26 16:37:06 GMT+03:00 2022) measure unt(cm) activity level(0) assisted weighing(false)
2022-02-26 16:46:15.983 Debug [2] OpenScale: Disconnecting from bluetooth device
2022-02-26 16:46:15.985 Debug [2] BluetoothCommunication: Bluetooth disconnect
2022-02-26 16:46:15.987 Info [2] BluetoothCentralManager: no scan to stop because no scan is running
2022-02-26 16:46:15.988 Error [2] BluetoothCentralManager: cannot cancel connection to unknown peripheral 5C:CA:D3:F8:EA:1D
2022-02-26 16:46:16.002 Debug [2] MainActivity: Bluetooth connection successful disconnected
2022-02-26 16:46:17.708 Debug [2] OpenScale: Trying to connect to bluetooth device [5C:CA:D3:F8:EA:1D] (SBF77)
2022-02-26 16:46:17.712 Debug [2] BluetoothCommunication: Do LE scan before connecting to device
2022-02-26 16:46:17.736 Info [2] BluetoothCentralManager: scan started
2022-02-26 16:46:17.738 Debug [2] BluetoothCommunication: Stop machine state
2022-02-26 16:46:18.388 Debug [2] BluetoothCommunication: Found peripheral 'SBF77'
2022-02-26 16:46:18.396 Info [2] BluetoothCentralManager: scan stopped
2022-02-26 16:46:19.399 Debug [2] BluetoothCommunication: Try to connect to BLE device 5C:CA:D3:F8:EA:1D
2022-02-26 16:46:19.504 Info [2] BluetoothPeripheral: connect to 'SBF77' (5C:CA:D3:F8:EA:1D) using transport LE
2022-02-26 16:46:19.510 Info [2] BluetoothPeripheral: peripheral '5C:CA:D3:F8:EA:1D' is connecting
2022-02-26 16:46:19.776 Info [3791] BluetoothPeripheral: connected to 'SBF77' (NONE) in 0.3s
2022-02-26 16:46:19.777 Debug [2] BluetoothPeripheral: discovering services of 'SBF77' with delay of 0 ms
2022-02-26 16:46:20.204 Debug [3791] BluetoothPeripheral: connection parameters: interval=7.5ms latency=0 timeout=5s
2022-02-26 16:46:21.244 Info [3791] BluetoothPeripheral: discovered 10 services for 'SBF77'
2022-02-26 16:46:21.249 Debug [2] BluetoothCommunication: connected to 'SBF77'
2022-02-26 16:46:21.251 Debug [2] BluetoothCommunication: Successful Bluetooth services discovered
2022-02-26 16:46:21.253 Debug [2] BluetoothCommunication: Resume machine state
2022-02-26 16:46:21.254 Debug [2] BluetoothCommunication: Step Nr 0
2022-02-26 16:46:21.256 Debug [2] BluetoothStandardWeightProfile: stepNr: 0 START
2022-02-26 16:46:21.258 Debug [2] BluetoothCommunication: Step Nr 1
2022-02-26 16:46:21.260 Debug [2] BluetoothStandardWeightProfile: stepNr: 1 READ_DEVICE_MANUFACTURER
2022-02-26 16:46:21.262 Debug [2] BluetoothCommunication: Invoke read bytes on 0x2a29 "manufacturer name string"
2022-02-26 16:46:21.264 Debug [2] BluetoothCommunication: Step Nr 2
2022-02-26 16:46:21.266 Debug [2] BluetoothStandardWeightProfile: stepNr: 2 READ_DEVICE_MODEL
2022-02-26 16:46:21.268 Debug [2] BluetoothCommunication: Invoke read bytes on 0x2a24 "model number string"
2022-02-26 16:46:21.270 Debug [2] BluetoothCommunication: Step Nr 3
2022-02-26 16:46:21.271 Debug [2] BluetoothStandardWeightProfile: stepNr: 3 WRITE_CURRENT_TIME
2022-02-26 16:46:21.275 Debug [2] BluetoothCommunication: Invoke write bytes [E6 07 02 1A 10 2E 15 06 45 01] on 0x2a2b "current time"
2022-02-26 16:46:21.277 Debug [2] BluetoothCommunication: Step Nr 4
2022-02-26 16:46:21.279 Debug [2] BluetoothStandardWeightProfile: stepNr: 4 SET_NOTIFY_WEIGHT_MEASUREMENT
2022-02-26 16:46:21.281 Debug [2] BluetoothCommunication: Invoke set notification on 0x2a9d "weight measurement"
2022-02-26 16:46:21.283 Debug [2] BluetoothCommunication: Stop machine state
2022-02-26 16:46:21.290 Debug [2] MainActivity: Bluetooth connection successful established
2022-02-26 16:46:21.293 Debug [2] BluetoothPeripheral: reading characteristic <00002a29-0000-1000-8000-00805f9b34fb>
2022-02-26 16:46:21.348 Debug [3791] BluetoothPeripheral: connection parameters: interval=48.8ms latency=0 timeout=5s
2022-02-26 16:46:21.458 Debug [2] BluetoothPeripheral: starting bonding with 'SBF77' (5C:CA:D3:F8:EA:1D)
2022-02-26 16:46:21.465 Debug [2] BluetoothPeripheral: pairing request received: PAIRING_VARIANT_PIN (0)
2022-02-26 16:46:23.843 Debug [3792] BluetoothPeripheral: connection parameters: interval=15.0ms latency=0 timeout=6s
2022-02-26 16:46:33.264 Error [3792] BluetoothPeripheral: read failed for characteristic <00002a29-0000-1000-8000-00805f9b34fb>, status 'AUTHORIZATION_FAILED'
2022-02-26 16:46:33.270 Debug [2] BluetoothStandardWeightProfile: Received manufacturer: 
2022-02-26 16:46:33.284 Debug [2] BluetoothPeripheral: reading characteristic <00002a24-0000-1000-8000-00805f9b34fb>
2022-02-26 16:46:33.286 Error [2] BluetoothPeripheral: bonding failed for 'SBF77', disconnecting device
2022-02-26 16:46:33.292 Error [3792] BluetoothPeripheral: read failed for characteristic <00002a24-0000-1000-8000-00805f9b34fb>, status 'ERROR'
2022-02-26 16:46:33.301 Info [3792] BluetoothPeripheral: peripheral 'SBF77' disconnected with status 'REMOTE_USER_TERMINATED_CONNECTION' (19)
2022-02-26 16:46:33.302 Debug [2] BluetoothStandardWeightProfile: Received modelnumber: 
2022-02-26 16:46:33.386 Debug [2] BluetoothCommunication: disconnected 'SBF77' with status 19

**Comment by wh8box** [comment]
App crush still stay, but bluetooth connection working after this reset manipulation:
[MIUI 12.5] Settings->Connection Sharing->Reset Wi-Fi, Mobile Network, and Bluetooth->Reset Settings
