### ISSUE TITLE
bug when first using app and standing on KASA Bluetooth scales from ebay

### ISSUE THREAD

**Issue by Captain-Glen** [oliexdev/openScale#840]
Build version: 2.4.5 
Build date: 1981-01-01 01:01:02 
Current date: 2022-03-16 22:09:37 
Device: ZTE Blade A30 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.IllegalStateException: Fragment BluetoothSettingsFragment{f675b24} (d96cc918-2c66-4c35-b0f9-04d2253db259) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.onDeviceFound(BluetoothSettingsFragment.java:204)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.access$000(BluetoothSettingsFragment.java:69)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$1$1.run(BluetoothSettingsFragment.java:131)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

KASA brand scales from eBay.  Works really well except for this trivial bug below.

**To Reproduce**
1. Open OpenScale
2. Stand on scales
3. Attempt to pair scales
4. See error message below

Work around:
Ignore bug and enjoy OpenScale from F-Droid.

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???

**Expected behavior**

**Additional context**

**Debug log**
Attach a debug log (see Settings -> About -> Save debug log to file) that is captured while reproducing the issue.

**Comment by Captain-Glen** [comment]
OK so, my work around no longer works.

But it looks like the app needs location permission to use Bluetooth.  But it doesn't ask!

You have to go into settings and turn it on.

To do this click "hamburger" --> settings --> Bluetooth --> search for your bluetooth scale.

It should then ask for location permission.

This bug effects the paid version also.

**Comment by Captain-Glen** [comment]
So it seems broken again:

I think this is a hardware issue, where the repair on my phone by "professionals" partially wrecked the Bluetooth.  :'(

Build version: 2.4.5 
Build date: 1981-01-01 01:01:02 
Current date: 2022-03-27 07:43:49 
Device: Motorola moto g(8) power lite 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.IllegalStateException: Fragment BluetoothSettingsFragment{2d3ec5e} (fd961630-3562-4a97-9f2d-e4632a75fa58) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.onDeviceFound(BluetoothSettingsFragment.java:204)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.access$000(BluetoothSettingsFragment.java:69)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$1$1.run(BluetoothSettingsFragment.java:131)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by Captain-Glen** [comment]
Yep definately a hardware issue.  It works on a different phone at stock settings (+ f-droid).

Never trust a professional.

It would be nice if there was a prompt that took you to the choose Bluetooth device screen though.
