### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by kbot82** [oliexdev/openScale#841]
The app crashed while looking on 'statistics'. 

Log:

Build version: 2.4.5 
Build date: 1981-01-01 01:01:02 
Current date: 2022-03-25 12:45:12 
Device: Xiaomi M2011K2G 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.IllegalStateException: Fragment BluetoothSettingsFragment{838bcda} (11fd5b6a-ffc6-41bb-b1c5-a74d36e306c1) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.onDeviceFound(BluetoothSettingsFragment.java:204)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.access$000(BluetoothSettingsFragment.java:69)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$1$1.run(BluetoothSettingsFragment.java:131)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8085)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by oliexdev** [comment]
I guess you were searching for a Bluetooth scale in the settings and then close it before the searching was finished.
