### ISSUE TITLE
Error while syncing Google Fit 

### ISSUE THREAD

**Issue by insac** [oliexdev/openScale#862]
**Describe the bug**
When launching the "Manual full sync" it returns an unexpected error. The erro le detail seem to point to a data point with weight 102.85 but the only recent one (it worked regularly some week ago) seem legit with hour and minutes.

Error details:
Build version: 0.3.4 
Build date: 1981-01-01 01:01:02 
Current date: 2022-05-31 22:33:00 
Device: OnePlus GM1913 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.IllegalArgumentException: Data point does not have the timestamp set: DataPoint{[102.85]@[0, 0,raw=0](r:weight:com.health.openscale.sync: N/A)}
	at q1.o.c(Unknown Source:9)
	at com.google.android.gms.fitness.data.DataSet$a.a(:12)
	at com.health.openscale.sync.core.sync.a.d(:12)
	at z3.a$c.onClick(:12)
	at android.view.View.performClick(View.java:7520)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3600(View.java:826)
	at android.view.View$PerformClick.run(View.java:28555)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**To Reproduce**
1. Go to 'Google fit'
2. Click on 'Manual full sync'
3. Funny big picture with "An unexpected error occurred" and the instructions to open an issue.

Reproduced with 0.3.4: current version on Google Play

**Expected behavior**
Data to be sync with my Google Fit account

**Additional context**

**Debug log**
[openScaleSync_2022-05-31_22-32.txt](https://github.com/oliexdev/openScale/files/8809297/openScaleSync_2022-05-31_22-32.txt)

**Comment by insac** [comment]
No, ok.. I solved it. I extracted the data in Excel to see if there were a couple of weights that had a date of 01/01/1970. I deleted them and now it works. So the right question would be, how those weights with corrupted date end up in my OpenScale db, but on that I don't have a clue

**Comment by insac** [comment]
Closing the issue
