### ISSUE TITLE
Exception if you switch from portrait to landscape mode

### ISSUE THREAD

**Issue by AlBundy33** [oliexdev/openScale#889]
... whine in user or bluetooth settings
```
Build version: 2.4.6 
Build date: 1981-01-01 01:01:02 
Current date: 2022-10-24 23:20:01 
Device: Google Pixel 2 XL 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.health.openscale/com.health.openscale.gui.MainActivity}: android.view.InflateException: Binary XML file line #34 in com.health.openscale:layout/activity_main: Binary XML file line #34 in com.health.openscale:layout/activity_main: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5456)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5362)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #34 in com.health.openscale:layout/activity_main: Binary XML file line #34 in com.health.openscale:layout/activity_main: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #34 in com.health.openscale:layout/activity_main: Error inflating class fragment
Caused by: java.lang.IllegalArgumentException: ID does not reference a View inside this Activity
	at android.app.Activity.requireViewById(Activity.java:3375)
	at androidx.core.app.ActivityCompat.requireViewById(ActivityCompat.java:368)
	at androidx.navigation.Navigation.findNavController(Navigation.kt:48)
	at com.health.openscale.gui.preferences.BluetoothPreferences.onCreateView(BluetoothPreferences.java:82)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:394)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:260)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:295)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:274)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1067)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
	at com.health.openscale.gui.MainActivity.onCreate(MainActivity.java:172)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5456)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5362)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by oliexdev** [comment]
Should be fixed in the latest version
