### ISSUE TITLE
Error connecting to RENPHO ES-32MD via Bluetooth with my Pixel 4 phone

### ISSUE THREAD

**Issue by bigheart2** [oliexdev/openScale#909]
Build version: 2.4.6 
Build date: 1981-01-01 01:01:02 
Current date: 2023-01-05 19:14:23 
Device: Google Pixel 4a 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.NullPointerException: no valid characteristic provided
	at java.util.Objects.requireNonNull(Objects.java:245)
	at com.welie.blessed.BluetoothPeripheral.writeCharacteristic(BluetoothPeripheral.java:1202)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.writeBytes(BluetoothCommunication.java:303)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.writeBytes(BluetoothCommunication.java:291)
	at com.health.openscale.core.bluetooth.BluetoothQNScale.onNextStep(BluetoothQNScale.java:111)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:599)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:601)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:601)
	at com.health.openscale.core.bluetooth.BluetoothCommunication.access$000(BluetoothCommunication.java:48)
	at com.health.openscale.core.bluetooth.BluetoothCommunication$2.onConnectedPeripheral(BluetoothCommunication.java:494)
	at com.welie.blessed.BluetoothCentralManager$6$2.run(BluetoothCentralManager.java:231)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by oliexdev** [comment]
please reply to this thread --> https://github.com/oliexdev/openScale/issues/905#issuecomment-1398443621
