### ISSUE TITLE
Application failed 

### ISSUE THREAD

**Issue by vlk12345** [oliexdev/openScale#934]
Build version: 2.5.1-pro 
Build date: 1981-01-01 01:01:02 
Current date: 2023-02-28 23:07:52 
Device: HMD Global Nokia 6.1 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.health.openscale.gui.table.StickyHeaderTableView.updateMaxWidthHeightOfCell(StickyHeaderTableView.java:611)
	at com.health.openscale.gui.table.StickyHeaderTableView.onMeasure(StickyHeaderTableView.java:421)
	at android.view.View.measure(View.java:24534)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:452)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:750)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:503)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solvingPass(Direct.java:224)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:693)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24534)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:24534)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
	at android.view.View.measure(View.java:24534)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3004)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1831)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2120)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1719)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7602)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:799)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by oliexdev** [comment]
see #935
