### ISSUE TITLE
Crash on Bluetooth Scan Unknown Permission

### ISSUE THREAD

**Issue by mikeloeven** [oliexdev/openScale#952]
App crash on any attempt to add scale. Given the error appears to say BLUETOOTH_SCAN is a unknown permision this may be due to my phone being anolder s5 variant with an older android build. Hopefully this can be resolved eaisly

Build version: 2.5.1 
Build date: 1981-01-01 01:01:02 
Current date: 2023-04-14 06:40:11 
Device: Samsung SAMSUNG-SM-G870A 
OS version: Android 6.0.1 (SDK 23) 
 
Stack trace:  
java.lang.IllegalArgumentException: Unknown permission: android.permission.BLUETOOTH_SCAN
	at android.os.Parcel.readException(Parcel.java:1624)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.content.pm.IPackageManager$Stub$Proxy.shouldShowRequestPermissionRationale(IPackageManager.java:3673)
	at android.app.ApplicationPackageManager.shouldShowRequestPermissionRationale(ApplicationPackageManager.java:604)
	at android.app.Activity.shouldShowRequestPermissionRationale(Activity.java:4214)
	at androidx.core.app.ActivityCompat$Api23Impl.shouldShowRequestPermissionRationale(ActivityCompat.java:898)
	at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:600)
	at androidx.fragment.app.FragmentActivity$HostCallbacks.onShouldShowRequestPermissionRationale(FragmentActivity.java:640)
	at androidx.fragment.app.Fragment.shouldShowRequestPermissionRationale(Fragment.java:1703)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment.onResume(BluetoothSettingsFragment.java:202)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:3180)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:771)
	at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:690)
	at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:877)
	at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:176)
	at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:126)
	at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:306)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1912)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by oliexdev** [comment]
should be fixed please try out the openScale dev version @ https://github.com/oliexdev/openScale/releases/tag/dev-build.
