### ISSUE TITLE
Bug on connecting to RENPHO Elis 1 (Model: ES-30M-US)

### ISSUE THREAD

**Issue by KurosubiGT** [oliexdev/openScale#986]
I tried to get a "smart scale" and the ES-30M-US was listed in the compatible list. But maybe my scale is different as it is the "USB rechargeable" version. It also have the Bluetooth name of QN-Scale. 
Amazon product number (ASIN) of the scale I purchased: ‎**B079DQ7JK6** 

The app don't have issues to see my scale and add it, but once I step on the scale, it give me an error and ask me to post the log here. Sorry to not be able to give more information. 

### Error log from OpenScale:
```
Build version: 2.5.2-pro 
Build date: 1981-01-01 01:01:02 
Current date: 2023-08-25 19:05:51 
Device: Samsung SM-S908W 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.NullPointerException: no valid characteristic provided
 at j$.util.Objects.requireNonNull(Unknown Source:5)
 at com.welie.blessed.BluetoothPeripheral.writeCharacteristic(BluetoothPeripheral.java:1229)
 at com.health.openscale.core.bluetooth.BluetoothCommunication.writeBytes(BluetoothCommunication.java:303)
 at com.health.openscale.core.bluetooth.BluetoothCommunication.writeBytes(BluetoothCommunication.java:291)
 at com.health.openscale.core.bluetooth.BluetoothQNScale.onNextStep(BluetoothQNScale.java:111)
 at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:610)
 at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:612)
 at com.health.openscale.core.bluetooth.BluetoothCommunication.nextMachineStep(BluetoothCommunication.java:612)
 at com.health.openscale.core.bluetooth.BluetoothCommunication.resumeMachineState(BluetoothCommunication.java:210)
 at com.health.openscale.core.bluetooth.BluetoothCommunication$1.onServicesDiscovered(BluetoothCommunication.java:464)
 at com.welie.blessed.BluetoothPeripheral$1$1.run(BluetoothPeripheral.java:210)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8757)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by oliexdev** [comment]
Since there has been no progress on this issue for a long time, I am closing it for now.  

Please note that implementation of new scale support requires access to the **actual scale**.

If someone wants to continue working on this, feel free to **reopen this issue** or submit a working implementation via a **pull request**.

For guidance on how to add a new scale handler into openScale, see the updated wiki page:  **[How to support a new scale](https://github.com/oliexdev/openScale/wiki/How-to-support-a-new-scale)**
